// <auto-generated />
namespace ModelosDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class agregandoStockProducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregandoStockProducts));
        
        string IMigrationMetadata.Id
        {
            get { return "202605152326277_agregandoStockProducts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
