//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesTelefono
    {
        public int Id { get; set; }
        public string NumeroTelefonico { get; set; }
        public int CompaniaTelefonicaId { get; set; }
        public int PersonaId { get; set; }
    
        public virtual CompaniasTelefonica CompaniasTelefonica { get; set; }
        public virtual Personas Personas { get; set; }
    }
}
