//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identidades
    {
        public int Id { get; set; }
        public string Identificacion { get; set; }
        public int TipoIdentificacionId { get; set; }
        public int PersonaId { get; set; }
    
        public virtual Personas Personas { get; set; }
        public virtual TiposIdentificacion TiposIdentificacion { get; set; }
    }
}
