//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelosDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBStoreEntities : DbContext
    {
        public DBStoreEntities()
            : base("name=DBStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompaniasTelefonica> CompaniasTelefonica { get; set; }
        public virtual DbSet<DetallesTelefono> DetallesTelefono { get; set; }
        public virtual DbSet<Identidades> Identidades { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<TiposIdentificacion> TiposIdentificacion { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<DetallesEntrada> DetallesEntrada { get; set; }
        public virtual DbSet<Entradas> Entradas { get; set; }
        public virtual DbSet<Marcas> Marcas { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<SubCategorias> SubCategorias { get; set; }
    }
}
